#!/bin/bash
# vim:syntax=sh:foldmethod=marker

# GNUPLOT SCRIPT {{{
GNUPLOT=$(cat <<EOF
set terminal pngcairo
set output "month.png"
set xtics rotate
set grid

plot \
"-" using 1:3:xtic(2) title "Avg" with lines, \
"-" using 1:4:xtic(2) title "Bal" with lines, \
"-" using 1:5:xtic(2) title "In" with lines, \
"-" using 1:6:xtic(2) title "Out" with lines
EOF
)
# }}}

INPUT=$(cat - | fin-month-prepare-plot)
D="\ne\n"

echo -en "$GNUPLOT\n$INPUT$D$INPUT$D$INPUT$D$INPUT$D" | gnuplot
